apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-pod-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-pod
  template:
    metadata:
      labels:
        app: api-pod
    spec:
      containers:
      - name: api-pod-container
        image: api-pod-image  # Use the name of your Docker image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80  # Port on which your Python application runs (if applicable)